# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  

  - title: Developer docs
    output: web, pdf
    folderitems:
    - title: Developer docs
      url: /DevDocsLanding.html
      output: web

    - title: Sample 1
      url: /ErrorLogging.html
      output: web, pdf

    - title: Sample 2
      url: /p1_sample2.html
      output: web, pdf

    - title: Sample 3
      url: /p1_sample3.html
      output: web, pdf

  

# Copyright 2021 Google LLC
