# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  

  - title: API and developer docs
    output: web
    folderitems:
    
    - title: Introduction to API and developer docs
      url: /DevDocsLanding.html
      output: web
    - title: SMS Integration
      url: /SmsIntegration.html
      output: web
    - title: Error Logging
      url: /ErrorLogging.html
      output: web

  


